# Generated by Django 5.2.8 on 2025-11-23 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Protocolo')),
                ('nome_solicitante', models.CharField(max_length=100, verbose_name='Nome')),
                ('empresa', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100, verbose_name='Contato (Email/Tel)')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('aguardando', 'Aguardando Resposta'), ('respondido', 'Respondido'), ('em_progresso', 'Em Progresso'), ('em_espera', 'Em Espera'), ('resolvido', 'Resolvido')], default='novo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='tickets.ticket')),
            ],
        ),
    ]
